name: Build and Push
on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Force update submodules
        run: |
          git submodule update --remote --merge

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.0'
          extended: true

      - name: Clean up old Hugo public folder
        run: rm -rf jpl

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install postcss
        run: npm i postcss postcss-cli autoprefixer

      - name: Build embedded react widget
        working-directory: ./mappin-itslive-embed
        run: npm install && npm run build-prod

      - name: Build react app
        working-directory: ./mappin
        run: npm install && npm run build-prod

      - name: Build for jpl
        run: hugo --minify -b https://its-live.jpl.nasa.gov/ -d jpl -e production

      - name: Deploy to jpl branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jpl
          publish_branch: jpl
